name: example
description: Example for flutter_translate_gen

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_translate_annotations: ^2.0.0

dev_dependencies:
  flutter_translate_gen:
    path: ../
  build_runner: ^2.1.1
