name: flutter_translate_gen
description: Statically-typed localization keys generator for flutter_translate.
version: 2.0.0
homepage: https://leadcode.dev
repository: https://github.com/bratan/flutter_translate_gen
publish_to: none

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  analyzer: ^1.5.0
  async: ^2.5.0
  build: ^2.0.1
  code_builder: ^4.0.0
  dart_casing: ^1.0.1
  dart_style: ^2.0.0
  dart_utils: ^1.0.2
  flutter_translate_annotations:
    git:
      url: https://github.com/seasox/flutter_translate_annotations
      ref: camel_case_keys
  glob: ^2.0.1
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.1
