name: flutter_translate_gen
description: Statically-typed localization keys generator for flutter_translate.
version: 1.2.4
author: Florin Bratan <florin@leadcode.dev>
homepage: https://leadcode.dev
repository: https://github.com/bratan/flutter_translate_gen

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dart_casing: ^1.0.1
  dart_utils: ^1.0.2
  source_gen: '>=0.9.4 <1.0.0'
  build: '>=1.2.1 <2.0.0'
  code_builder: '>=3.2.0 <4.0.0'
  analyzer: '>=0.36.4 <1.0.0'
  glob: ^1.2.0
  flutter_translate_annotations: ^1.0.1

dev_dependencies:
  build_runner: '>=1.7.0 <2.0.0'
