name: flutter_translate_gen
description: Statically-typed localization keys generator for flutter_translate.
version: 2.0.0
homepage: https://leadcode.dev
repository: https://github.com/bratan/flutter_translate_gen

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.5.0
  async: ^2.5.0
  build: ^2.0.1
  code_builder: ^4.0.0
  dart_casing: ^1.0.1
  dart_style: ^2.0.0
  dart_utils: ^1.0.2
  flutter_translate_annotations: ^2.0.0
  glob: ^2.0.1
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.1

dependency_overrides:
  dart_casing:
    git:
      url: https://github.com/McCrafterIV/dart_casing.git
  dart_utils:
    git:
      url: https://github.com/McCrafterIV/dart_utils.git

